/**
 * Prompt builder for the visual QA evaluator.
 *
 * Kept as a pure function separate from the Anthropic provider
 * so:
 *   - the system prompt is testable without a network call
 *   - future providers reuse the same rubric-encoding logic
 *   - rubric changes ripple through one place
 *
 * DESIGN NOTES:
 *
 * The system prompt commits the model to a strict JSON schema
 * (mirroring VisualQaResultSchema in ./schema.ts). Every
 * rubric criterion is enumerated with its name and summary so
 * the model can't miss one — the runtime Zod validator ALSO
 * requires one `checks[]` entry per criterion in practice
 * (schema uses .min(1) but the prompt asks for all N).
 *
 * We ask the model to return ONE `hasHardFailure` boolean; the
 * decision engine cross-checks it against a locally-computed
 * value from the rubric so a hallucinated "false" doesn't
 * silently approve a broken clip.
 *
 * The user-message content mixes text + reference image (if
 * present) + the asset (image OR ordered video frames). The
 * provider is responsible for assembling those into its own
 * content blocks; this module only produces the STRINGS.
 */

import type { RubricCriterion } from "./rubric";
import type { VisualQaInput } from "./visual-qa-provider";

/** Fixed lead-in the system prompt always starts with. Exported
 *  for tests that want to pin the version-independent portion. */
export const QA_SYSTEM_PROMPT_HEADER = `You are a visual QA evaluator for TikTok Shop content videos generated by an AI content pipeline.

Your job is to score the given asset against a fixed rubric and return STRUCTURED JSON only. You do NOT decide what happens next (regeneration, approval, etc.) — a separate deterministic engine does that. Your only job is to observe and report.

You MUST return exactly one JSON object matching this schema, with no prose before or after, no markdown fences, no explanation:

{
  "overallScore": <integer 0-100>,
  "hasHardFailure": <boolean>,
  "checks": [
    {
      "name": <one of the rubric criterion names below>,
      "passed": <boolean>,
      "score": <integer 0-100>,
      "severity": <"soft" | "major" | "critical", optional — only when passed=false>,
      "reason": <string, optional — one-line explanation>,
      "frameTimestampMs": <integer, optional — for videos, the frame timestamp where the issue was observed>
    }
  ],
  "issues": [
    {
      "type": <short kebab-case slug for the defect, e.g. "label_warp">,
      "severity": <"soft" | "major" | "critical">,
      "description": <one-line human-readable description>,
      "frameTimestampMs": <integer, optional>,
      "suggestedRepair": <string, optional — a concrete instruction the next generation could use>
    }
  ]
}

Rules:
- Emit ONE check per rubric criterion. Missing a criterion is a validation failure.
- Emit an issue for EVERY defect the operator would want to see, even if it doesn't fail a rubric criterion.
- hasHardFailure=true means the asset is unusable and MUST be regenerated. Reserve it for: wrong/missing product, major product morphing, product count changes, severe label corruption, severe hand deformation, prominent malformed text, floating/disappearing objects, obvious generation breakdown.
- overallScore is a holistic 0-100 quality read. Approximate anchor: 90+ excellent (ready to post), 80-89 good, 60-79 usable-with-review, <60 clearly defective.
- Severity guide:
    critical  = the asset is unusable
    major     = a real defect an operator would want to catch
    soft      = informational — worth noting, doesn't block use
- If a criterion's check passes, omit severity + reason.
- Prefer positive framing in reasons ("label is sharp and readable" over "no label warping").`;

/** Build the full system prompt for a QA call. Includes the
 *  header + a data table of the rubric criteria the model must
 *  score against. */
export function buildQaSystemPrompt(rubric: readonly RubricCriterion[]): string {
  const rubricBlock = rubric
    .map(
      (c) =>
        `- ${c.name}: ${c.summary}`,
    )
    .join("\n");
  return `${QA_SYSTEM_PROMPT_HEADER}\n\nRubric criteria (emit one check per criterion, using the exact name):\n${rubricBlock}`;
}

/**
 * Build the user-message text (the non-image portion of the
 * user turn). The provider assembles this with image blocks in
 * its own content array; this function returns only the text.
 *
 * The text tells the model:
 *   - what asset it's looking at (type + scene label)
 *   - product context so it can judge SCENE_APPROPRIATENESS
 *   - which market so the retail scene reads right
 *   - the original generation prompt when we have it (so the
 *     model can weight "did it follow the prompt" implicitly)
 *   - whether there's a reference image and, for videos, how
 *     many frames it will receive and their timestamps
 *
 * Everything the model needs is in this text; images come as
 * separate content blocks after.
 */
export function buildQaUserText(input: VisualQaInput): string {
  const lines: string[] = [];

  lines.push(`Asset type: ${input.assetType}`);
  lines.push(`Scene label: ${input.sceneLabel}`);
  lines.push(`Product: ${input.productName}`);
  if (input.productCategory) {
    lines.push(`Category: ${input.productCategory}`);
  }
  lines.push(`Market: ${input.market.toUpperCase()}`);
  lines.push("");

  if (input.generationPrompt) {
    lines.push("Generation prompt that produced this asset (verbatim):");
    lines.push('"""');
    lines.push(input.generationPrompt);
    lines.push('"""');
    lines.push("");
  }

  if (input.referenceImage) {
    lines.push(
      "The FIRST image you receive is the ORIGINAL PRODUCT REFERENCE image (as captured on the source listing). Score PRODUCT_FIDELITY against this image.",
    );
  } else {
    lines.push(
      "NOTE: No original product reference image is on file for this product. Score PRODUCT_FIDELITY loosely — you have nothing to compare against directly, so rate based only on internal plausibility (does the product look like a plausible real product, does its label/branding look consistent within the asset?).",
    );
  }

  if (input.asset.kind === "image") {
    lines.push(
      input.referenceImage
        ? "The SECOND image you receive is the GENERATED ASSET to evaluate."
        : "The image you receive is the GENERATED ASSET to evaluate.",
    );
  } else {
    const count = input.asset.frames.length;
    const timestamps = input.asset.frames
      .map((f) => (f.timestampMs / 1000).toFixed(2) + "s")
      .join(", ");
    lines.push(
      input.referenceImage
        ? `The NEXT ${count} images you receive are FRAMES from the GENERATED VIDEO, in order. Their timestamps (from clip start) are: ${timestamps}.`
        : `You will receive ${count} FRAMES from the GENERATED VIDEO, in order. Their timestamps (from clip start) are: ${timestamps}.`,
    );
    lines.push(
      "When reporting per-frame issues, use frameTimestampMs (integer milliseconds).",
    );
  }

  lines.push("");
  lines.push("Return the JSON object now. No prose, no markdown.");

  return lines.join("\n");
}
